### ISSUE TITLE
Enforce no-space policy in app and team names (to make simple urls a bit simpler, without escaped whitespaces)

### ISSUE THREAD

**Issue by bartosz-jarmuz** [bartosz-jarmuz/Telimena#4]
The team and project names should only allow letters, numbers and -. No whitespace, no national characters etc.

These are used to generate a friendly URL - so the URL shouldn't contain escaped character crap.

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by bartosz-jarmuz** [comment]
That's done, cheers.
